/*
SELECT
FROM

DUAL -> 가상테이블, 임시테이블

*/

SELECT 1, 'A' FROM DUAL;
SELECT 'A' FROM DUAL;
SELECT TO_DATE('20211222','YYYYMMDD') FROM DUAL;

/*
SELECT
FROM
WHERE -> 조건절 IF

비교연산자 ( > < >= <= <> )
NULL, IS NULL, IS NOT NULL
&& -> AND,|| -> OR, ( )

*/
--이름이 JULIA라는 사람을 찾아라.
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME = 'JULIA' 

--급여가 9000이상인 사람만 찾아라.
SELECT first_name, SALARY
FROM EMPLOYEES
WHERE SALARY >= 9000;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 9000;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEE
--이름이 SHANTA보다 큰 이름. (철자보다 큰이름)
SELECT first_name
FROM EMPLOYEES
WHERE FIRST_NAME > 'SHANTA'

--이름의 첫 스펠링이 j보다 큰 이름.
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME > 'J';

--매니저(상사)가 없는 사원.
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

--보너스가 없는 사람.
SELECT FIRST_NAME, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;
    
--보너스가 있는 사람.
SELECT FIRST_NAME, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

--AND
SELECT FIRST_NAME, LAST_NAME --두가지 조건이 참이 되어야 함.
FROM EMPLOYEES
WHERE FIRST_NAME = 'SHANTA'
AND LAST_NAME = 'VOLLMAN';

--이름 JOHN, 월급 5000이상.
SELECT first_name, salary
FROM EMPLOYEES
WHERE FIRST_NAME = 'JOHN';
AND SALARY >= 5000;

--2007년 12월 31일 이후에 입사한 사원을 출력
SELECT first_name, hire_date  
FROM EMPLOYEES
WHERE hire_date > '07/12/31';

SELECT first_name, hire_date  
FROM EMPLOYEES
--WHERE HIRE_DATE > '20071231'; -> 이렇게 사용해도 가능.
WHERE hire_date > TO_DATE ('20071231','YYYYMMDD');--정석 형식

--ALL(==AND), ANY(==OR)
SELECT *
FROM EMPLOYEES
--WHERE FIRST_NAME = ALL('JULIA','JOHN');
WHERE FIRST_NAME = 'JULIA' AND FIRST_NAME = 'JOHN';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = ANY('JULIA','JOHN');

--월급이 8000,3200,6000인 사람을 출력.
SELECT first_name, SALARY
FROM EMPLOYEES
WHERE SALARY = ANY(8000, 3200, 6000);

--IN, NOT IN
SELECT FIRST_NAME, salary
FROM EMPLOYEES
WHERE SALARY IN(8000, 3200, 6000);

SELECT FIRST_NAME, salary
FROM EMPLOYEES
WHERE SALARY NOT IN(8000, 3200, 6000);

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME IN('JULIA','JOHN');
--WHERE FIRST_NAME = 'JULIA' OR FIRST_NAME = 'JOHN';

--BETWEEN 범위 연산자
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
--WHERE SALARY >=3200 AND SALARY <=9000;
WHERE SALARY BETWEEN 3200 AND 9000;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 3200 AND 9000;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = 9000;

SELECT FIRST_NAME, COMMISSION_PCT
FROM EMPLOYEES
WHERE commission_pct IS NULL;
    

