--LIKE
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'G_RA_D'; --_는 한글자를 의미

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'K%Y'; --%는 글자 수에 관계없이 모두 허용

--A라는 사람을 찾아라
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'a%';

--Y가 맨끝에 끝나는 사람을 찾아라
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%y';

--중간에 e가 들어간 사람을 찾아라
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%e%';

--'%' || "투표"|| '%'

--006년도에 입사한 사람을 검색
SELECT first_name,hire_date
FROM EMPLOYEES
WHERE HIRE_DATE > '05/12/31' AND hire_date < '07/01/01';

SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '06%'

--590이 들어간 번호를 출력해라
SELECT FIRST_NAME, PHONE_NUMBER
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '590%'; 

SELECT FRIST_NAME, PHONE_NUMBER, SALARY
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '590%'AND SALARY > 5000
