/*
ORDER BY == SORTHING

SELECT  COLUMN VALUE SUBQUERY
FROM    TABLE SUBQUERRY
WHERE   IF
ORDER   BY COLUMN ASC  오름(생략가능)
                  DESC 내림
DESC 테이블명 -> 명세 --잘안씀.

*/

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY ASC; -- 오름차순

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC; -- 내림차순

--ALIAS //현재 정렬하고 싶은 데이터를 설정.
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY * 12 AS ANNSAL
FROM EMPLOYEES
--ORDER BY SALARY * 12 DESC; 내림차순으로 연봉 정리.
ORDER BY ANNSAL DESC;

--null FIRST
SELECT commission_pct
FROM EMPLOYEES
ORDER BY COMMISSION_PCT NULLS FIRST; --NULL이 먼저 출력 됨.

SELECT commission_pct
FROM EMPLOYEES
ORDER BY COMMISSION_PCT NULLS LAST; --NULL이 마지막에 출력됨.

SELECT commission_pct, SALARY
FROM EMPLOYEES
ORDER BY COMMISSION_PCT NULLS LAST, SALARY DESC; --SALARY가 역순으로 정렬이 됨.

--입사순으로 정렬을 한 뒤, 급여는 역순으로 정리.
SELECT HIRE_DATE, SALARY, JOB_ID
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC, SALARY DESC;

--업무명으로 정렬을 한후, 급여를 역순으로 정렬
SELECT JOB_ID, SALARY
FROM EMPLOYEES
ORDER BY JOB_ID ASC, SALARY DESC;



