/*
    SEQUENCE : 유일한 값을 생성해 주는 오라클 오브젝트
                NUMBER++;
*/

-- SEQUENCE 생성
CREATE SEQUENCE TEST_SEQ
INCREMENT BY 1      -- 1씩 증가
START WITH 10       -- 시작 숫자
MAXVALUE 100
MINVALUE 1;

-- CURRVAL = 현재의 SEQ
SELECT TEST_SEQ.CURRVAL 
FROM DUAL;

-- NEXTVAL = 진행 값
SELECT TEST_SEQ.NEXTVAL 
FROM DUAL;

-- 수정
ALTER SEQUENCE TEST_SEQ
INCREMENT BY 3;

DROP SEQUENCE TEST_SEQ;

